# Generated by Django 3.1.6 on 2021-02-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicatie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicatie.sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BinaryField(null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicatie.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicatie.user')),
            ],
        ),
    ]
